name: iOS starter workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: xcodebuild clean test -project "BLECombineKit.xcodeproj" -scheme "BLECombineKit" -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
